### ISSUE TITLE
Feature: User can view homepage

### ISSUE THREAD

**Issue by daisyyoo** [daisyyoo/Hope-Care-Hospice#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User will be able to view homepage

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
The user will be able to view the homepage with the information of the company displayed. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to correctly fetch the route for homepage
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks
- [x] Create a component to have the landing page for home page
  - [x] Input most details manually into this page
  - [x] Keep it simple, some information and pictures only.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
