### ISSUE TITLE
User can view About Us 

### ISSUE THREAD

**Issue by daisyyoo** [daisyyoo/Hope-Care-Hospice#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the About Us page.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view the About Us page by clicking on the header or modal nav bar
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103452411/214459073-f51c30e4-a035-4b69-bc27-323a4098e852.png)
![image](https://user-images.githubusercontent.com/103452411/214459601-0d34fb7c-9bd8-47c9-9b23-f32ee80f7dd8.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
  - [x] Show wrong page if error?
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to render about us page

### 🧑‍⚕️ Clean Up Tasks
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
